language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
  -
before_script: chmod 0555 ./node_modules/.bin/jest

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
script:
  - jest --coverage --coverageReporters=text-lcov | coveralls
  - npm test
